// Generated by https://quicktype.io

export interface Capabilities {
  basemaps: Basemaps;
  tilesets: Tileset[];
}

export interface Basemaps {
  WMTS: Wmt[];
  vectorTile: any[];
}

export interface Wmt {
  name: string;
  attribution: string;
  url: string;
  layer: string;
  tile_matrix_set: string;
}

export interface Tileset {
  url: string;
  tilejson: Tilejson;
  name: string;
  description: string;
  version: Version;
  attribution: Attribution;
  template: string;
  legend: string;
  scheme: Scheme;
  tiles: string[];
  grids: any[];
  tags: string[];
  data: any[];
  minzoom: number;
  maxzoom: number;
  bounds: number[];
  center: number[];
}

export enum Attribution {
  AHrefHTTPOpenstreetmapOrgOSMContributorsA = "<a href='http://openstreetmap.org'>OSM contributors</a>",
}

export enum Scheme {
  Xyz = 'xyz',
}

export enum Tilejson {
  The220 = '2.2.0',
}

export enum Version {
  The100 = '1.0.0',
}
